/**
 * @fileoverview Swagger DTOs for 400 Validation Error responses in the Auth module.
 *
 * Field-level constraint messages inside `errors[]` are generated by class-validator.
 */
import { ApiProperty } from '@nestjs/swagger';
import { UserRole } from '@prisma/client';
import {
  FieldErrorDto,
  ValidationErrorResponseDto,
} from 'src/common/dto/validation-error.dto';
import { Methods } from 'src/common/enum/methods.enum';

const VALIDATION_MSG_EXAMPLE = 'Validation failed';

// ─── Register ─────────────────────────────────────────────────────────────────

export class RegisterValidationErrorResponseDto extends ValidationErrorResponseDto {
  @ApiProperty({ example: VALIDATION_MSG_EXAMPLE })
  declare message: string;

  @ApiProperty({ example: Methods.POST })
  declare method: Methods;

  @ApiProperty({ example: '/api/auth/register' })
  declare endpoint: string;

  @ApiProperty({
    type: [FieldErrorDto],
    example: [
      { field: 'fullName', message: 'fullName must be a string' },
      { field: 'email', message: 'email must be a valid email address' },
      { field: 'password', message: 'password must be at least 8 characters' },
      {
        field: 'role',
        message: `role must be one of: ${Object.values(UserRole).join(', ')}`,
      },
    ],
  })
  declare errors: FieldErrorDto[];
}

// ─── Verify Account ───────────────────────────────────────────────────────────

export class VerifyAccountValidationErrorResponseDto extends ValidationErrorResponseDto {
  @ApiProperty({ example: VALIDATION_MSG_EXAMPLE })
  declare message: string;

  @ApiProperty({ example: Methods.POST })
  declare method: Methods;

  @ApiProperty({ example: '/api/auth/verify-account' })
  declare endpoint: string;

  @ApiProperty({
    type: [FieldErrorDto],
    example: [
      { field: 'email', message: 'email must be a valid email address' },
      { field: 'otp', message: 'otp must be exactly 6 characters' },
    ],
  })
  declare errors: FieldErrorDto[];
}

// ─── Resend Verification Email ────────────────────────────────────────────────

export class ResendVerificationOtpValidationErrorResponseDto extends ValidationErrorResponseDto {
  @ApiProperty({ example: VALIDATION_MSG_EXAMPLE })
  declare message: string;

  @ApiProperty({ example: Methods.POST })
  declare method: Methods;

  @ApiProperty({ example: '/api/auth/resend-verification-otp' })
  declare endpoint: string;

  @ApiProperty({
    type: [FieldErrorDto],
    example: [
      { field: 'email', message: 'email must be a valid email address' },
    ],
  })
  declare errors: FieldErrorDto[];
}

// ─── Login ────────────────────────────────────────────────────────────────────

export class LoginValidationErrorResponseDto extends ValidationErrorResponseDto {
  @ApiProperty({ example: VALIDATION_MSG_EXAMPLE })
  declare message: string;

  @ApiProperty({ example: Methods.POST })
  declare method: Methods;

  @ApiProperty({ example: '/api/auth/login' })
  declare endpoint: string;

  @ApiProperty({
    type: [FieldErrorDto],
    example: [
      { field: 'email', message: 'email must be a valid email address' },
      { field: 'password', message: 'password should not be empty' },
    ],
  })
  declare errors: FieldErrorDto[];
}

// ─── Forgot Password ──────────────────────────────────────────────────────────

export class ForgotPasswordValidationErrorResponseDto extends ValidationErrorResponseDto {
  @ApiProperty({ example: VALIDATION_MSG_EXAMPLE })
  declare message: string;

  @ApiProperty({ example: Methods.POST })
  declare method: Methods;

  @ApiProperty({ example: '/api/auth/forgot-password' })
  declare endpoint: string;

  @ApiProperty({
    type: [FieldErrorDto],
    example: [
      { field: 'email', message: 'email must be a valid email address' },
    ],
  })
  declare errors: FieldErrorDto[];
}

// ─── Verify OTP ───────────────────────────────────────────────────────────────

export class VerifyOtpValidationErrorResponseDto extends ValidationErrorResponseDto {
  @ApiProperty({ example: VALIDATION_MSG_EXAMPLE })
  declare message: string;

  @ApiProperty({ example: Methods.POST })
  declare method: Methods;

  @ApiProperty({ example: '/api/auth/forget-password-verify-otp' })
  declare endpoint: string;

  @ApiProperty({
    type: [FieldErrorDto],
    example: [
      { field: 'email', message: 'email must be a valid email address' },
      {
        field: 'otp',
        message: 'otp must be longer than or equal to 6 characters',
      },
    ],
  })
  declare errors: FieldErrorDto[];
}

// ─── Reset Password ───────────────────────────────────────────────────────────

export class ResetPasswordValidationErrorResponseDto extends ValidationErrorResponseDto {
  @ApiProperty({ example: VALIDATION_MSG_EXAMPLE })
  declare message: string;

  @ApiProperty({ example: Methods.POST })
  declare method: Methods;

  @ApiProperty({ example: '/api/auth/reset-password' })
  declare endpoint: string;

  @ApiProperty({
    type: [FieldErrorDto],
    example: [
      {
        field: 'reset_token',
        message: 'reset_token should not be empty',
      },
      {
        field: 'newPassword',
        message: 'newPassword must be at least 8 characters',
      },
    ],
  })
  declare errors: FieldErrorDto[];
}

// ─── Refresh Token ────────────────────────────────────────────────────────────

export class RefreshTokenValidationErrorResponseDto extends ValidationErrorResponseDto {
  @ApiProperty({ example: VALIDATION_MSG_EXAMPLE })
  declare message: string;

  @ApiProperty({ example: Methods.POST })
  declare method: Methods;

  @ApiProperty({ example: '/api/auth/refresh-token' })
  declare endpoint: string;

  @ApiProperty({
    type: [FieldErrorDto],
    example: [
      {
        field: 'refresh_token',
        message: 'refresh_token must be a valid refresh token',
      },
    ],
  })
  declare errors: FieldErrorDto[];
}

// ─── Change Email — Initiate ──────────────────────────────────────────────────

export class ChangeEmailInitiateValidationErrorResponseDto extends ValidationErrorResponseDto {
  @ApiProperty({ example: VALIDATION_MSG_EXAMPLE })
  declare message: string;

  @ApiProperty({ example: Methods.POST })
  declare method: Methods;

  @ApiProperty({ example: '/api/auth/change-email/initiate' })
  declare endpoint: string;

  @ApiProperty({
    type: [FieldErrorDto],
    example: [
      { field: 'newEmail', message: 'newEmail must be a valid email address' },
    ],
  })
  declare errors: FieldErrorDto[];
}

// ─── Change Email — Verify ────────────────────────────────────────────────────

export class ChangeEmailVerifyValidationErrorResponseDto extends ValidationErrorResponseDto {
  @ApiProperty({ example: VALIDATION_MSG_EXAMPLE })
  declare message: string;

  @ApiProperty({ example: Methods.POST })
  declare method: Methods;

  @ApiProperty({ example: '/api/auth/change-email/verify' })
  declare endpoint: string;

  @ApiProperty({
    type: [FieldErrorDto],
    example: [{ field: 'otp', message: 'otp must be exactly 6 digits' }],
  })
  declare errors: FieldErrorDto[];
}

// ─── Change Password ──────────────────────────────────────────────────────────

export class ChangePasswordValidationErrorResponseDto extends ValidationErrorResponseDto {
  @ApiProperty({ example: VALIDATION_MSG_EXAMPLE })
  declare message: string;

  @ApiProperty({ example: Methods.POST })
  declare method: Methods;

  @ApiProperty({ example: '/api/auth/change-password' })
  declare endpoint: string;

  @ApiProperty({
    type: [FieldErrorDto],
    example: [
      { field: 'oldPassword', message: 'oldPassword should not be empty' },
      {
        field: 'newPassword',
        message: 'newPassword must be at least 8 characters',
      },
    ],
  })
  declare errors: FieldErrorDto[];
}
