/**
 * @fileoverview Swagger DTOs for 400 Validation Error responses.
 *
 * The top-level `message` field is localized at runtime based on the `lang`
 * request header (`en` | `bn`).  Field-level constraint messages inside the
 * `errors` array are generated by class-validator and remain in English.
 */
import { ApiProperty } from '@nestjs/swagger';
import { Methods } from '../enum/methods.enum';

/**
 * Represents a single field-level validation failure.
 */
export class FieldErrorDto {
  @ApiProperty({ example: 'name' })
  field!: string;

  @ApiProperty({ example: 'name must be a string' })
  message!: string;
}

/**
 * Represents a 400 Bad Request response for validation failures.
 *
 * The `message` field is localized:
 * - EN: `"Validation failed"`
 * - BN: `"যাচাইকরণ ব্যর্থ হয়েছে"`
 */
export class ValidationErrorResponseDto {
  @ApiProperty({ example: false })
  success!: boolean;

  @ApiProperty({
    example: 'Validation failed',
    description:
      'localized top-level message. ' +
      'EN: "Validation failed" | ' +
      'BN: "যাচাইকরণ ব্যর্থ হয়েছে"',
  })
  message!: string;

  @ApiProperty({ example: Methods.POST })
  method!: Methods;

  @ApiProperty({ example: '/' })
  endpoint!: string;

  @ApiProperty({ example: 400 })
  statusCode!: number;

  @ApiProperty({ example: '2026-02-22T10:00:00.000Z' })
  timestamp!: string;

  @ApiProperty({ type: [FieldErrorDto] })
  errors!: FieldErrorDto[];
}
